### ISSUE TITLE
Spell lists could have limited sizes

### ISSUE THREAD

**Issue by tassaron** [tassaron/dnd-character#18]
The library could provide some assistance by limiting the size of the spell lists.

- [x] `self._spells_known` should not exceed `self.spell_slots["spells_known"]`
- [x] `self._cantrips_known` should not exceed `self.spell_slots["cantrips_known"]`
- [x] Add function to get max size of `spells_prepared` (I think it's class level + spellcasting ability modifier)
- [x] `self._spells_prepared` should not exceed this size from aforementioned function

**Comment by gergo-szabo** [comment]
What is the intended function of `self.spell_slots["spells_known"]` and `self.spell_slots["cantrips_known"]`?
It seems redundant if we have `self._spells_known` and `self._cantrips_known`. I think spell slot calculation/tracking should be a relatively independent feature from known spells/cantrips.

**Comment by tassaron** [comment]
Those two values are the maximum numbers of spells and cantrips that the player character can learn. They should be renamed to have `maximum_` before the names perhaps, so it's easier to understand.

The `spell_slots` property on Character is a direct copy of a dict from the JSON from the SRD API, so it is a bit weird. Maybe we should change the names of all the keys in this dict.
